### ISSUE TITLE
Can't use template variables in queries

### ISSUE THREAD

**Issue by jreineke-nli** [camptocamp/grafana-prometheus-alertmanager-datasource#10]
With version 0.0.3 the ability to use variables queries has been added.
Unfortunately i can't get this to work for me in Grafana.

When I'm using my variables in the query the datasource won't regonize them as a variable and just prints "$variable" in the url to get the data from the alertmanager.

Is there something im doing wrong here?

**Comment by SPampel** [comment]
I can reproduce this for the single stat in 0.0.3.

When I create a variable in the dashboard it gets properly replaced by it's value:

Metrik query:
`alertname="$alertname"`

Query Inspector:
> xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/1/api/v1/alerts?silenced=false&filter=alertname%3D%22Blackbox_Exporter_Probe_Failure%22"
data:Object
timezone:"browser"
panelId:3
range:Object
rangeRaw:Object
interval:"15s"
intervalMs:15000
targets:Array[1]
format:"json"
maxDataPoints:1259
scopedVars:Object
cacheTimeout:undefined
response:Object
status:"success"
data:Array[1]
0:Object



Make sure you select the format of the metric as "single" for singlestat and table for tables. Otherwise it doesn't seam to work.

**Comment by jreineke-nli** [comment]
I just tried it again with a custom label from prometheus:

`customer="$customer"`

```
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/2/api/v1/alerts?silenced=false&filter=customer%3D%22%24customer%22"
data:Object
timezone:"browser"
panelId:21
range:Object
rangeRaw:Object
interval:"15m"
intervalMs:900000
targets:Array[1]
format:"json"
maxDataPoints:100
scopedVars:Object
cacheTimeout:null
response:Object
status:"success"
data:Array[0]
```

Default variables like alertname or instance won't work here either.
I think somewhere outside the plugin itself is an entry that causes my problem. I installed the version 0.0.1 and updated manually to 0.0.3 and tryed to reinstalled it without any success.

**Comment by cryptobioz** [comment]
I've been able to reproduce, the variable support was not enabled for the "single" format.
This issue is now fixed, I also added the support of "All" and "Multi" values.
