### ISSUE TITLE
Query box disappears when trying to set variable

### ISSUE THREAD

**Issue by ngpadp12** [camptocamp/grafana-prometheus-alertmanager-datasource#105]
I have configured alertmanager as a datasource and trying to create variables out of it.

However, when I select it as the datasource for my variable, the query box disappears and I am left with only the Regex box.

![image](https://user-images.githubusercontent.com/20218353/120422818-c0a4ec80-c386-11eb-8110-81ada79ea111.png)

When I add a regex, it gives me the following error:
![image](https://user-images.githubusercontent.com/20218353/120428458-4af24e00-c391-11eb-9630-1a2123ee7e03.png)

The regex I am using is this -> /"dimension_ServiceName":"(.*?)"/

Could you please help me with this? Not sure where I am going wrong.

**Comment by guerricm** [comment]
same issue after upgrading to grafana 8.0.3

**Comment by hbollon** [comment]
Hi @guerricm,
This behavior is normal since _grafana-prometheus-alertmanager-datasource_ doesn't support queries for variables. It may change in the future but atm what you tried to do is impossible directly on this datasource.
In order to do what you tried to achieve, you must define a variable with raw values or query directly a Prometheus datasource.
