### ISSUE TITLE
In grafana 5.2.1 : plugin seems broken

### ISSUE THREAD

**Issue by ludopaquet** [camptocamp/grafana-prometheus-alertmanager-datasource#39]
With this version of grafana, we have this plugin error:
`Error: Failed to fetch Instantiating public/vendor/plugin-css/css.js 
Loading /public/vendor/plugin-css/css.js 
Instantiating public/plugins/camptocamp-prometheus-alertmanager-datasource/css/query-editor.css!/public/vendor/plugin-css/css.js 
Loading /public/plugins/camptocamp-prometheus-alertmanager-datasource/query_ctrl.js 
Loading plugins/camptocamp-prometheus-alertmanager-datasource/module
`

**Comment by FUSAKLA** [comment]
There is issue that after upgrade the severity mapping got erased which is invalid for the plugin and you have to fill it in again and there. 

In my case after filling in the severity mapping it works fine again.

**Comment by ludopaquet** [comment]
Thanks for your answer, which file did you change ?

**Comment by FUSAKLA** [comment]
I did not changed any file just go to datasources in Grafana user interface edit the alertmanager datasource and specify the severities in datasource configuration.

That fixed it for me

**Comment by FUSAKLA** [comment]
Ok so this is different issue I had the datasource created before the Grafana upgrade

I tried on `5.2.0` and I'm able to create new Alertmanager datasource


so it has to be the `5.2.1` changes what caused this probably
https://github.com/grafana/grafana/releases/tag/v5.2.1

I see the footer bug that should be fixed in the `5.2.1` but nothing else relevant 

will try upgrading to `5.2.1` to reproduce

**Comment by ludopaquet** [comment]
FYI no more issues on 5.2.3
