### ISSUE TITLE
Variable containing special characters

### ISSUE THREAD

**Issue by DMOsipov** [camptocamp/grafana-prometheus-alertmanager-datasource#62]
Hi, 

In my dashboard I have variable `$instance` containing IP address of monitored host, for example 127.0.0.1
If I specify filter expression  `instance="$instance"` then empty resultset is returned from the prometheus alert manager. In query inspector I can see that all dots in IP address escaped with two backslashes and than URI-encoded:

>api/datasources/proxy/2/api/v1/alerts?silenced=false&inhibited=false&filter=instance%3D%22127%5C%5C.0%5C%5C.0%5C%5C.1%22"

and of course alert manager is unable to find alerts with `instance=127\\.0\\.0\\.1`

Investigating the issue I found that fix #40 added new function `interpolateQueryExpr` calling `dsSpecialRegexEscape` with very string escape functionality. I have no idea why so many escapes are required, but seems those escape function is the root cause of my issue.

**Comment by hbollon** [comment]
Hey @DMOsipov,
Sorry for the (very) late response 😓
This issue should be now solved since few releases, if you're always using our plugin maybe you could give a try to the new [v1.1.0](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/releases/tag/v1.1.0) :wink: 
I'm closing this but don't hesitate to open new issues.
