### ISSUE TITLE
Variables - template variable could not be initialized

### ISSUE THREAD

**Issue by RazcoDev** [camptocamp/grafana-prometheus-alertmanager-datasource#71]
Hey guys.
Unfortunately when I'm trying to add alermanager data-source variable, I'm encountering a weird error from Grafana that says : "template variable could not be initialized : t.metricFindQuery is not a function.

No matter what I'm typing on the query field, it throws me that error.

My purpose is to set a variable with all the alert names I have on AlertManager.

Can anyone show me an exist variable as an example?
Thank you very much,
Raz Cohen.

**Comment by chelomontilla** [comment]
I'm also interested.
Could you please provide an example on how to add a variable?
Thanks

**Comment by wangyf123** [comment]
Interested, too.
Wait for reply.

**Comment by hbollon** [comment]
Hi everyone!
Actually, this plugin doesn't support queries for variables. It may change in the future but atm what you tried to do is impossible directly on the _camptocamp-prometheus-alertmanager-datasource_ datasource.
In order to do what you tried to achieve, you must define a variable with raw values or query directly a Prometheus datasource.
